//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Gerenciador_de_Consultorio.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Persist Security Info=True;Username=postgres;Host=localHost;Database=Sistema_de_G" +
            "erenciamento_de_Consultorio")]
        public string Sistema_de_Gerenciamento_de_ConsultorioConnectionString {
            get {
                return ((string)(this["Sistema_de_Gerenciamento_de_ConsultorioConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Database=teste;Host=localHost;Username=postgres;Password=679-6951;Persist Securit" +
            "y Info=True")]
        public string testeConnectionString {
            get {
                return ((string)(this["testeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Host=localHost;Database=Sistema_Gerenciador_de_Consultorio;Username=postgres;Pass" +
            "word=679-6951;Persist Security Info=True")]
        public string Sistema_Gerenciador_de_Consultorio_Nova_Conexão {
            get {
                return ((string)(this["Sistema_Gerenciador_de_Consultorio_Nova_Conexão"]));
            }
        }
    }
}
