INSERT INTO endereco(cidade,idUsuario) VALUES ('Gurupi',1);
INSERT INTO endereco(cidade,idUsuario) VALUES ('Campinas',1);
INSERT INTO endereco(cidade,idUsuario) VALUES ('Vitória da Conquista',1);
INSERT INTO endereco(cidade,idUsuario) VALUES ('Japeri',1);
INSERT INTO endereco(cidade,idUsuario) VALUES ('Palmas',1);
INSERT INTO endereco(cidade,idUsuario) VALUES ('Blumenau',1);
INSERT INTO endereco(cidade,idUsuario) VALUES ('Blumenau',1);
INSERT INTO endereco(cidade,idUsuario) VALUES ('Aracruz',1);
INSERT INTO endereco(cidade,idUsuario) VALUES ('Igarassu',1);
INSERT INTO endereco(cidade,idUsuario) VALUES ('Salvador',1);
INSERT INTO endereco(cidade,idUsuario) VALUES ('Ribeirão das Neves',1);
INSERT INTO endereco(cidade,idUsuario) VALUES ('Guarapari',1);
INSERT INTO endereco(cidade,idUsuario) VALUES ('Várzea Grande',1);
INSERT INTO endereco(cidade,idUsuario) VALUES ('Várzea Grande',1);
INSERT INTO endereco(cidade,idUsuario) VALUES ('Limeira',1);
INSERT INTO endereco(cidade,idUsuario) VALUES ('Valparaíso de Goiás',1);
INSERT INTO endereco(cidade,idUsuario) VALUES ('Altamira',1);
INSERT INTO endereco(cidade,idUsuario) VALUES ('Porto Alegre',1);
INSERT INTO endereco(cidade,idUsuario) VALUES ('Macapá',1);
INSERT INTO endereco(cidade,idUsuario) VALUES ('Natal',1);
INSERT INTO endereco(cidade,idUsuario) VALUES ('Salvador',1);
INSERT INTO endereco(cidade,idUsuario) VALUES ('Boa Vista',1);
INSERT INTO endereco(cidade,idUsuario) VALUES ('Crato',1);
INSERT INTO endereco(cidade,idUsuario) VALUES ('Belém',1);
INSERT INTO endereco(cidade,idUsuario) VALUES ('Maranguape',1);
INSERT INTO endereco(cidade,idUsuario) VALUES ('Porto Alegre',1);
INSERT INTO endereco(cidade,idUsuario) VALUES ('Teresópolis',1);
INSERT INTO endereco(cidade,idUsuario) VALUES ('João Pessoa',1);
INSERT INTO endereco(cidade,idUsuario) VALUES ('Manaus',1);
INSERT INTO endereco(cidade,idUsuario) VALUES ('Brasília',1);
